name: Deploy to A.D.S. Games

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GAME_ID: solitairejs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: yarn
      
    - name: Install dependencies
      run: yarn --frozen-lockfile
        
    - name: Build
      run: yarn build
      
    - name: Get tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
    - name: Set up S3cmd cli tool
      uses: s3-actions/s3cmd@v1.2.0
      with:
        provider: linode
        region: 'us-east-1'
        access_key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
        secret_key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}

    - name: Push build
      run: |
        s3cmd sync --recursive --acl-public dist/* s3://ads-games/games/${{ env.GAME_ID }}/${{ steps.vars.outputs.tag }}/


