name: Deploy to A.D.S. Games

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: yarn
      
    - name: Install dependencies
      run: yarn --frozen-lockfile
        
    - name: Build
      run: yarn build

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Deploy to A.D.S. Games
      uses: adsgames/deploy-to-adsgames@main
      with:
        project-id: solitaire
        version: ${{ steps.get_version.outputs.VERSION }}
        build-dir: dist
        platform: WEB
        bucket-access-key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
        bucket-secret-key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
        api-key: ${{ secrets.ADSGAMES_API_KEY }}

