name: Build Game

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12
        cache: yarn

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Lint project
      run: yarn lint
      
    - name: Build project
      run: yarn build
